name: Bug report
description: Report a defect in kernel, userland, build, or CI behavior.
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Provide enough detail to reproduce and validate a fix.
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - kernel
        - userland
        - build-tooling
        - CI
        - docs
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: OS, compiler/toolchain, QEMU version, commit hash/tag
    validations:
      required: true
